### ISSUE TITLE
WebSocket section needs updating

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-mixed-content#27]
It looks very unaware of the current status quo of WebSocket specifications (which might soonish change again, but updates to reference Fetch and HTML as appropriate would be good).

**Comment by mikewest** [comment]
Hrm. Interesting! I guess we're not using the RFC at all anymore... Looking at Fetch and HTML, I'm not actually sure there's any monkey-patching to do. I'll just reword the integration with HTML/Fetch sections to highlight how they affect WebSockets as well.

**Comment by domenic** [comment]
I ran into this today. It looks like you could just delete https://w3c.github.io/webappsec-mixed-content/#websockets-integration, or replace it with a sentence pointing to the fact that https://fetch.spec.whatwg.org/#websocket-protocol means that mixed content blocking automatically applies to WebSockets too.
