### ISSUE TITLE
Level 2 story for <form>

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-mixed-content#28]
If the goal of Level 2 is to avoid having tri-state UI, it seems more work is needed regarding https://w3c.github.io/webappsec-mixed-content/#requirements-forms, no?

**Comment by mikewest** [comment]
cc @estark37 @carlosjoan91

**Comment by sideshowbarker** [comment]
@annevk Do you consider the change in #48 to be a satisfactory resolution to this issue?

If so, @carlosjoan91 can we close this issue, or is there some remaining need to keep it open?

I see that in #48, you wrote:

> This addresses #28 (though not closing yet in case other changes for `<form>` come up).

I guess no other changes for `<form>` ended up ever coming up?

**Comment by carlosjoan91** [comment]
Happy to close since nothing regarding forms came up, we can always create a new, more specific issue if needed.
