### ISSUE TITLE
Update to account for removal of HTTPS state

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-mixed-content#32]
HTTPS state has been removed and this document does not account for that. I'm also not entirely sure it defines the right logic for workers. In particular data: URL workers might need some more consideration.

If this specification is being maintained I can look into writing a PR, but the open PR does not seem reassuring.

cc @domenic

**Comment by estark37** [comment]
@carlosjoan91 I wonder if this is something you might be able to take on (or review a PR if @annevk sends one)?

We should fix this at least in Level 2 if not in Level 1.

**Comment by carlosjoan91** [comment]
Yeah, happy to review or write a PR. @annevk: Are you still planning to write the PR? Otherwise let me know and I'll write one.

**Comment by annevk** [comment]
If you could take it @carlosjoan91 that'd be great. Happy to review.

**Comment by carlosjoan91** [comment]
Sure, I'll send a PR.
