### ISSUE TITLE
References to [mixed-content] don't point to the level 1 spec

### ISSUE THREAD

**Issue by jyasskin** [w3c/webappsec-mixed-content#58]
https://www.w3.org/TR/mixed-content/#category-upgradeable says

> Upgradeable content was previously referred to as optionally-blockable in [mixed-content]

but that reference points to Mixed Content Level 2. It, and at least most of the other uses of [mixed-content] should point to level 1 instead.

**Comment by annevk** [comment]
FWIW, I think the solution here should be to simply remove the reference and adjust the sentence so it can stand on its own. For instance:

> Upgradeable content was previously referred to as optionally-blockable.

**Comment by jyasskin** [comment]
There are 5 references to the level 1 spec that can probably all go away, but they'll each take a bit of editing.

**Comment by sideshowbarker** [comment]
> There are 5 references to the level 1 spec that can probably all go away, but they'll each take a bit of editing.

I opened #57 for this. Please take a look there and let me know if I missed anything
