### ISSUE TITLE
Republish CR.

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec-mixed-content#6]
I think we should republish our CR to include exciting normative changes we've made recently:

https://w3c.github.io/webappsec-mixed-content/CR.html is up for your review.

+1s and emojified responses welcome here. Alternatively, if you think something's not ready yet, file an issue and I'll link it up here.

CfC posted to the list at https://lists.w3.org/Archives/Public/public-webappsec/2016Jul/0033.html.

**Comment by wseltzer** [comment]
Done, thanks!

**Comment by mikewest** [comment]
Thank you!
